regime: B

simulation:
  # Barkley parameter ---------------------------
  a: 0.75
  b: 0.06
  epsilon: 0.08
  alpha: 3

  # Simulation quanities ------------------------
  starting_condition: chaotic # two_spirals, chaotic
  dt: 0.01
  ds: 0.1
  D: 0.02 
  size: [120,120,120] # Cube size

  init_phase: random

  last_state_file: None

  # Save settings -------------------------------
  dSave: 16 # Sequence discretization for saving in [*ds]
  max_save_length: 32 # Sequence length
  num_sims: 16 # How many independent simulation with one call
  dataset: regimeB

   
training:
  device: cuda
  config_file: conf/base/training.yml

prediction:
  regime: B
  model: STLSTM
  batch_size: 2
  device: cuda
  name: "STLSTM_t_1_6_12_17_22_27_32_d_31"
  depths: [30]
  time_steps: [0,5,11,16,21,26,31]

validation:
  name: "STLSTM_t_1_6_12_17_22_27_32_d_31"
  depths: [30]
  loss: mae # mae, mse

  
  
  
  
  
  
  
