regimeA:
  # Barkley parameter ---------------------------
  a: 0.6
  b: 0.01
  epsilon: 0.02
  alpha: 1

  # Simulation quanities ------------------------
  starting_condition: two_spirals # two_spirals, chaotic
  dt: 0.01
  ds: 0.1
  D: 0.02 
  size: [120,120,120] # Cube size

  # Save settings -------------------------------
  dSave: 16 # Sequence discretization for saving in [*ds]
  max_save_length: 32 # Sequence length
  num_sims: 16 # How many independent simulation with one call
  dataset: regimeA
  
regimeB:
  # Barkley parameter ---------------------------
  a: 0.75
  b: 0.06
  epsilon: 0.08
  alpha: 3

  # Simulation quanities ------------------------
  starting_condition: chaotic # two_spirals, chaotic
  dt: 0.01
  ds: 0.1
  D: 0.02 
  size: [120,120,120] # Cube size

  # Save settings -------------------------------
  dSave: 16 # Sequence discretization for saving in [*ds]
  max_save_length: 32 # Sequence length
  num_sims: 16 # How many independent simulation with one call
  dataset: regimeB
  
  
prediction:
  regime: A
  model: STLSTM
  batch_size: 8
  device: cuda
  name: "STLSTM_t32_d32"
  depths: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]

validation:
  model: STLSTM
  depths: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
  loss: mae # mae, mse
  
  
  
  
  
  
  
  
  
